### ISSUE TITLE
cp: cannot create regular file

### ISSUE THREAD

**Issue by ankkax** [nitanmarcel/waydroid-magisk-installer#2]
tried to install on arch and ubuntu touch fresh waydroid install and I get
`cp: cannot create regular file '/tmp/tmp.s6dOzx3sF6/system/system/etc/init//magisk/magisk64': No such file or directory`

**Comment by nitanmarcel** [comment]
> tried to install on arch and ubuntu touch fresh waydroid install and I get `cp: cannot create regular file '/tmp/tmp.s6dOzx3sF6/system/system/etc/init//magisk/magisk64': No such file or directory`

Post the full logs please :)

**Comment by nitanmarcel** [comment]
Should be fixed. Redownload `install.sh` Do a clean install and try again :)

**Comment by ankkax** [comment]
It worked great job! thank you :)

**Comment by nitanmarcel** [comment]
> It worked great job! thank you :)

Be free to close the issue if you don't have any problems :)
